### ISSUE TITLE
Proofread chapters

### ISSUE THREAD

**Issue by onlurking** [onlurking/category-theory-for-programmers#1]
### Part One

- [x] Category: The Essence of Composition
- [x] Types and Functions
- [ ] Categories Great and Small
- [ ] Kleisli Categories
- [ ] Products and Coproducts
- [ ] Simple Algebraic Data Types
- [ ] Functors
- [ ] Functoriality
- [ ] Function Types
- [ ] Natural Transformations

### Part Two

- [ ] Declarative Programming
- [ ] Limits and Colimits
- [ ] Free Monoids
- [ ] Representable Functors
- [ ] The Yoneda Lemma
- [ ] Yoneda Embedding

### Part Three

- [ ] It’s All About Morphisms
- [ ] Adjunctions
- [ ] Free/Forgetful Adjunctions
- [ ] Monads: Programmer’s Definition
- [ ] Monads and Effects
- [ ] Monads Categorically
- [ ] Comonads
- [ ] F-Algebras
- [ ] Algebras for Monads
- [ ] Ends and Coends
- [ ] Kan Extensions
- [ ] Enriched Categories
- [ ] Topoi
- [ ] Lawvere Theories
- [ ] Monads, Monoids, and Categories
